// import { Box } from "@mantine/core";
// import { useNavigate } from "react-router-dom";
// import { hasAnyPermission } from "../utils/permission";
// import { PERMISSIONS } from "../enums/permissions";
// import { useEffect } from "react";

// const AdminDashboard = () => {
//   const navigate = useNavigate();

//   // Permission checks
//   const isSuperAdmin = hasAnyPermission([
//     PERMISSIONS.VIEW_FOLDERS,
//     PERMISSIONS.MANAGE_ROLES,
//     PERMISSIONS.BYPASS_PERMISSIONS,
//     PERMISSIONS.MANAGE_PERMISSIONS,
//     PERMISSIONS.VIEW_PERMISSIONS,
//     PERMISSIONS.MANAGE_ROLE_PERMISSIONS,
//     PERMISSIONS.VIEW_ROLE_PERMISSIONS,
//     PERMISSIONS.MANAGE_SUBCITIES,
//     PERMISSIONS.VIEW_SUBCITIES,
//     PERMISSIONS.MANAGE_USERS,
//     PERMISSIONS.VIEW_USERS,
//     PERMISSIONS.MANAGE_NEWS_CATEGORIES,
//     PERMISSIONS.VIEW_NEWS_CATEGORIES,
//     PERMISSIONS.MANAGE_NEWS,
//     PERMISSIONS.MANAGE_NEWS_MEDIA,
//     PERMISSIONS.VIEW_NEWS_MEDIA,
//     PERMISSIONS.MANAGE_GALLERIES,
//     PERMISSIONS.MANAGE_GALLERY_MEDIA,
//     PERMISSIONS.MANAGE_BOOK_CATEGORIES,
//     PERMISSIONS.MANAGE_BOOKS,
//     PERMISSIONS.MANAGE_COMPLAINTS,
//     PERMISSIONS.VIEW_COMPLAINTS,
//     PERMISSIONS.MANAGE_COMPLAINT_ATTACHMENTS,
//     PERMISSIONS.VIEW_COMPLAINT_ATTACHMENTS,
//     PERMISSIONS.MANAGE_COMPLAINT_NOTES,
//     PERMISSIONS.VIEW_COMPLAINT_NOTES,
//     PERMISSIONS.MANAGE_LEADERS,
//     PERMISSIONS.MANAGE_SUGGESTIONS,
//     PERMISSIONS.VIEW_SUGGESTIONS,
//     PERMISSIONS.MANAGE_SUGGESTION_ATTACHMENTS,
//     PERMISSIONS.VIEW_SUGGESTION_ATTACHMENTS,
//     PERMISSIONS.MANAGE_SUGGESTION_RESPONSES,
//     PERMISSIONS.VIEW_SUGGESTION_RESPONSES,
//     PERMISSIONS.MANAGE_VIDEO_CONFERENCES,
//     PERMISSIONS.VIEW_VIDEO_CONFERENCES,
//     PERMISSIONS.MANAGE_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.VIEW_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.MANAGE_CONFERENCE_RECORDINGS,
//     PERMISSIONS.VIEW_CONFERENCE_RECORDINGS,
//     PERMISSIONS.MANAGE_AUDIT_LOGS,
//     PERMISSIONS.VIEW_AUDIT_LOGS,
//     PERMISSIONS.ACCESS_ADMIN_DASHBOARD,
//     PERMISSIONS.MANAGE_SYSTEM_SETTINGS,
//   ]);

//   const isSubcityAdmin = hasAnyPermission([
//     PERMISSIONS.MANAGE_WOREDAS,
//     PERMISSIONS.VIEW_WOREDAS,
//     PERMISSIONS.MANAGE_USERS,
//     PERMISSIONS.VIEW_USERS,
//     PERMISSIONS.MANAGE_FOLDERS,
//     PERMISSIONS.VIEW_FOLDERS,
//     PERMISSIONS.MANAGE_FOLDER_SHARES,
//     PERMISSIONS.VIEW_FOLDER_SHARES,
//     PERMISSIONS.MANAGE_DOCUMENTS,
//     PERMISSIONS.VIEW_DOCUMENTS,
//     PERMISSIONS.MANAGE_DOCUMENT_METADATA,
//     PERMISSIONS.VIEW_DOCUMENT_METADATA,
//     PERMISSIONS.MANAGE_DOCUMENT_SHARES,
//     PERMISSIONS.VIEW_DOCUMENT_SHARES,
//     PERMISSIONS.MANAGE_NEWS_CATEGORIES,
//     PERMISSIONS.VIEW_NEWS_CATEGORIES,
//     PERMISSIONS.MANAGE_NEWS,
//     PERMISSIONS.MANAGE_NEWS_MEDIA,
//     PERMISSIONS.VIEW_NEWS_MEDIA,
//     PERMISSIONS.MANAGE_GALLERIES,
//     PERMISSIONS.MANAGE_GALLERY_MEDIA,
//     PERMISSIONS.MANAGE_BOOK_CATEGORIES,
//     PERMISSIONS.MANAGE_BOOKS,
//     PERMISSIONS.MANAGE_COMPLAINTS,
//     PERMISSIONS.VIEW_COMPLAINTS,
//     PERMISSIONS.MANAGE_COMPLAINT_ATTACHMENTS,
//     PERMISSIONS.VIEW_COMPLAINT_ATTACHMENTS,
//     PERMISSIONS.MANAGE_COMPLAINT_NOTES,
//     PERMISSIONS.VIEW_COMPLAINT_NOTES,
//     PERMISSIONS.MANAGE_LEADERS,
//     PERMISSIONS.MANAGE_SUGGESTIONS,
//     PERMISSIONS.VIEW_SUGGESTIONS,
//     PERMISSIONS.MANAGE_SUGGESTION_ATTACHMENTS,
//     PERMISSIONS.VIEW_SUGGESTION_ATTACHMENTS,
//     PERMISSIONS.MANAGE_SUGGESTION_RESPONSES,
//     PERMISSIONS.VIEW_SUGGESTION_RESPONSES,
//     PERMISSIONS.MANAGE_VIDEO_CONFERENCES,
//     PERMISSIONS.VIEW_VIDEO_CONFERENCES,
//     PERMISSIONS.MANAGE_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.VIEW_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.MANAGE_CONFERENCE_RECORDINGS,
//     PERMISSIONS.VIEW_CONFERENCE_RECORDINGS,
//     PERMISSIONS.MANAGE_CHAT_ROOMS,
//     PERMISSIONS.VIEW_CHAT_ROOMS,
//     PERMISSIONS.MANAGE_CHAT_MESSAGES,
//     PERMISSIONS.VIEW_CHAT_MESSAGES,
//     PERMISSIONS.MANAGE_CHAT_MESSAGE_ATTACHMENTS,
//     PERMISSIONS.VIEW_CHAT_MESSAGE_ATTACHMENTS,
//     PERMISSIONS.ACCESS_ADMIN_DASHBOARD,
//   ]);

//   const isWoredaAdmin = hasAnyPermission([
//     PERMISSIONS.MANAGE_USERS,
//     PERMISSIONS.VIEW_USERS,
//     PERMISSIONS.MANAGE_FOLDERS,
//     PERMISSIONS.VIEW_FOLDERS,
//     PERMISSIONS.MANAGE_FOLDER_SHARES,
//     PERMISSIONS.VIEW_FOLDER_SHARES,
//     PERMISSIONS.MANAGE_DOCUMENTS,
//     PERMISSIONS.VIEW_DOCUMENTS,
//     PERMISSIONS.MANAGE_DOCUMENT_METADATA,
//     PERMISSIONS.VIEW_DOCUMENT_METADATA,
//     PERMISSIONS.MANAGE_DOCUMENT_SHARES,
//     PERMISSIONS.VIEW_DOCUMENT_SHARES,
//     PERMISSIONS.MANAGE_COMMITTEES,
//     PERMISSIONS.VIEW_COMMITTEES,
//     PERMISSIONS.MANAGE_COMPLAINTS,
//     PERMISSIONS.VIEW_COMPLAINTS,
//     PERMISSIONS.MANAGE_COMPLAINT_ATTACHMENTS,
//     PERMISSIONS.VIEW_COMPLAINT_ATTACHMENTS,
//     PERMISSIONS.MANAGE_COMPLAINT_NOTES,
//     PERMISSIONS.VIEW_COMPLAINT_NOTES,
//     PERMISSIONS.MANAGE_SUGGESTIONS,
//     PERMISSIONS.VIEW_SUGGESTIONS,
//     PERMISSIONS.MANAGE_SUGGESTION_ATTACHMENTS,
//     PERMISSIONS.VIEW_SUGGESTION_ATTACHMENTS,
//     PERMISSIONS.MANAGE_SUGGESTION_RESPONSES,
//     PERMISSIONS.VIEW_SUGGESTION_RESPONSES,
//     PERMISSIONS.MANAGE_VIDEO_CONFERENCES,
//     PERMISSIONS.VIEW_VIDEO_CONFERENCES,
//     PERMISSIONS.MANAGE_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.VIEW_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.MANAGE_CONFERENCE_RECORDINGS,
//     PERMISSIONS.VIEW_CONFERENCE_RECORDINGS,
//     PERMISSIONS.MANAGE_CHAT_ROOMS,
//     PERMISSIONS.VIEW_CHAT_ROOMS,
//     PERMISSIONS.MANAGE_CHAT_MESSAGES,
//     PERMISSIONS.VIEW_CHAT_MESSAGES,
//     PERMISSIONS.MANAGE_CHAT_MESSAGE_ATTACHMENTS,
//     PERMISSIONS.VIEW_CHAT_MESSAGE_ATTACHMENTS,
//     PERMISSIONS.ACCESS_ADMIN_DASHBOARD,
//   ]);

//   const isOfficialAdmin = hasAnyPermission([
//     PERMISSIONS.MANAGE_FOLDERS,
//     PERMISSIONS.VIEW_FOLDERS,
//     PERMISSIONS.MANAGE_FOLDER_SHARES,
//     PERMISSIONS.VIEW_FOLDER_SHARES,
//     PERMISSIONS.MANAGE_DOCUMENTS,
//     PERMISSIONS.VIEW_DOCUMENTS,
//     PERMISSIONS.MANAGE_DOCUMENT_METADATA,
//     PERMISSIONS.VIEW_DOCUMENT_METADATA,
//     PERMISSIONS.MANAGE_DOCUMENT_SHARES,
//     PERMISSIONS.VIEW_DOCUMENT_SHARES,
//     PERMISSIONS.MANAGE_VIDEO_CONFERENCES,
//     PERMISSIONS.VIEW_VIDEO_CONFERENCES,
//     PERMISSIONS.MANAGE_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.VIEW_CONFERENCE_PARTICIPANTS,
//     PERMISSIONS.VIEW_CONFERENCE_RECORDINGS,
//     PERMISSIONS.MANAGE_CHAT_ROOMS,
//     PERMISSIONS.VIEW_CHAT_ROOMS,
//     PERMISSIONS.MANAGE_CHAT_MESSAGES,
//     PERMISSIONS.VIEW_CHAT_MESSAGES,
//     PERMISSIONS.MANAGE_CHAT_MESSAGE_ATTACHMENTS,
//     PERMISSIONS.VIEW_CHAT_MESSAGE_ATTACHMENTS,
//     PERMISSIONS.ACCESS_ADMIN_DASHBOARD,
//   ]);

//   // Redirect logic
//   useEffect(() => {
//     // Check in hierarchical order (most privileged first)
//     if (isSuperAdmin || isSubcityAdmin || isWoredaAdmin ||isOfficialAdmin) {
//       navigate("/dashboard");
//       return;
//     }

//     // Fallback for users with no matching permissions
//     navigate("/unauthorized");
//   }, [isSuperAdmin, isSubcityAdmin, isWoredaAdmin, isOfficialAdmin, navigate]);

//   // Display dashboard content if needed
//   return (
//     <Box>
          
//     </Box>
//   );
// };

// export default AdminDashboard;
