import {
  IconClipboardList,
  IconUserPlus,
  IconUsers,
  IconUserShare,
  IconFiles,
  IconNews,
  IconPhoto,
  IconQuestionMark,
  IconCalendarEvent,
  IconUsersGroup,
  IconUser,
  IconBuildingSkyscraper,
  IconBuildingCommunity,
  IconUsersPlus,
  IconBook,
  IconMail,
  IconAlertCircle,
  IconAlbum,
  IconChecklist,
  IconHierarchy,
  IconBulb,
  IconNotebook,
  IconFileDescription,
  IconBuildingBank,
  IconSpeakerphone,
  IconExternalLink,
  IconReportAnalytics,
  IconActivity,
} from "@tabler/icons-react";
import { PERMISSIONS } from "../enums/permissions";

export const menuItems = [
  {
    label: "Dashboard",
    to: "/dashboard/my-dashboard",
    icon: <IconUser size="1.125rem" />,
    permission: PERMISSIONS.VIEW_FOLDERS,
  },
  {
    label: "Registrations",
    icon: <IconClipboardList size="1.125rem" />,
    permission: PERMISSIONS.MANAGE_SUBCITIES,
    children: [
      {
        label: "Register Subcity",
        to: "/register/register-subcity",
        icon: <IconBuildingSkyscraper size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_SUBCITIES,
      },
      {
        label: "Register Woreda",
        to: "/register/register-woreda",
        icon: <IconBuildingCommunity size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Register Users",
        to: "/register/register-woreda-admins",
        icon: <IconUsersGroup size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_USERS,
      },
    ],
  },
  {
    label: "Role Management",
    icon: <IconUsers size="1.125rem" />,
    permission: PERMISSIONS.MANAGE_ROLES,
    children: [
      {
        label: "Create Role",
        to: "/role/create-role",
        icon: <IconUserPlus size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_ROLES,
      },
      {
        label: "Assign Permission to Role",
        to: "/role/assign-role",
        icon: <IconUserShare size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_ROLES,
      },
      {
        label: "View All Permissions",
        to: "/role/view-all-permissions",
        icon: <IconUserShare size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_ROLES,
      },
    ],
  },
  {
    label: "Video Conference",
    to: "/video-conference",
    icon: <IconFiles size="1.125rem" />,
    permission: PERMISSIONS.VIEW_FOLDERS,
  },
  {
    label: "Smart Chat",
    icon: <IconExternalLink size="1.125rem" />,
    permission: PERMISSIONS.VIEW_FOLDERS,
    isExternal: true,
  },
  {
    label: "Document Management",
    to: "/documents",
    icon: <IconFiles size="1.125rem" />,
    permission: PERMISSIONS.VIEW_FOLDERS,
  },
  {
    label: "Staff Management",
    to: "/staff-management",
    icon: <IconUsersPlus size="1.125rem" />,
    permission: PERMISSIONS.MANAGE_FOLDERS,
  },
  {
    label: "All Results",
    to: "/all-results",
    icon: <IconUsersPlus size="1.125rem" />,
    permission: PERMISSIONS.MANAGE_FOLDERS,
  },
  {
    label: "Questionnaires",
    to: "/questionnaires",
    icon: <IconQuestionMark size="1.125rem" />,
    permission: PERMISSIONS.VIEW_FOLDERS,
  },
  {
    label: "Tendency",
    to: "/tendency",
    icon: <IconActivity size="1.125rem" />,
    permission: PERMISSIONS.MANAGE_FOLDERS,
  },
  {
    label: "Tendency Report",
    to: "/tendency/report",
    icon: <IconReportAnalytics size="1.125rem" />,
    permission: PERMISSIONS.MANAGE_FOLDERS,
  },
  {
    label: "Content Management",
    icon: <IconNews size="1.125rem" />,
    permission: PERMISSIONS.MANAGE_WOREDAS,
    children: [
      {
        label: "Exhibition",
        to: "/cms/exibitions",
        icon: <IconSpeakerphone size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_W PLEASE
      },
      {
        label: "Exhibition Report",
        to: "/cms/exibitionsreport",
        icon: <IconSpeakerphone size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add News",
        to: "/cms/add-news",
        icon: <IconSpeakerphone size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add News Category",
        to: "/cms/add-news-category",
        icon: <IconSpeakerphone size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Carousel Images",
        to: "/cms/add-carousel-images",
        icon: <IconPhoto size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Gallery",
        to: "/cms/add-gallery",
        icon: <IconAlbum size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Post Video",
        to: "/cms/post-video",
        icon: <IconSpeakerphone size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Books",
        to: "/cms/add-books",
        icon: <IconBook size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Our Partners",
        to: "/cms/add-our-partners",
        icon: <IconBulb size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Head Of Government",
        to: "/cms/add-head-of-government",
        icon: <IconBuildingBank size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Head Of Subcity",
        to: "/cms/add-head-of-subcity",
        icon: <IconHierarchy size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Management Team",
        to: "/cms/add-management-team",
        icon: <IconUsersGroup size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Organizational Structure",
        to: "/cms/add-organizational-structure-users",
        icon: <IconBulb size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Woredas",
        to: "/cms/add-woredas",
        icon: <IconChecklist size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Announcements",
        to: "/cms/add-announcements",
        icon: <IconNotebook size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Tenders",
        to: "/cms/add-tenders",
        icon: <IconFileDescription size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "Add Events",
        to: "/cms/add-events",
        icon: <IconCalendarEvent size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "View Contacts",
        to: "/cms/view-contacts",
        icon: <IconMail size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
      {
        label: "View Complaints",
        to: "/cms/view-complaints",
        icon: <IconAlertCircle size="1.125rem" />,
        permission: PERMISSIONS.MANAGE_WOREDAS,
      },
    ],
  },
  {
    label: "Profile",
    to: "/profile/user-profile",
    icon: <IconUser size="1.125rem" />,
    permission: PERMISSIONS.VIEW_FOLDERS,
  },
];